server:
  port: ${PORT:3232}

spring:
  application:
    name: payments

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_URI:http://localhost:8080/realms/parking/protocol/openid-connect/certs}
          issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/parking}

  datasource:
    url: ${BD_URL:jdbc:postgresql://localhost:5432/parqueo}
    username: ${BD_USER:usertest}
    password: ${BD_PWD:123456}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8714/eureka/}

token:
  principal-attribute: preferred_username
  resource-id: parking-backend
  private-key: ${KEYCLOAK_TOKEN:ZgBAyWoHLGK7nJjQnLPvjYPrfbYibFy3}

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
