server:
  port: 3232

spring:
  application:
    name: payments

  datasource:
    url: jdbc:postgresql://localhost:5432/parqueo
    username: usertest
    password: 123456
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8714/eureka/
